// Generated by CoffeeScript 1.8.0
(function() {
  this.app = new Framework7();

  this.$$ = Dom7;

  this.loadLeader = function() {
    var viewLeader;
    viewLeader = this.app.addView("#view-leader", {
      dynamicNavbar: true
    });
    viewLeader.loadPage('leader.html');
    this.app.hideToolbar('#toolbar');
      this.app.onPageInit('leader-page', this.onInitLeader);
    this.app.onPageInit('index-edit-player', this.onInitIndexEditPlayer);
    this.app.onPageInit('edit-player', this.onInitEditPlayer);
    return this.app.onPageBack('edit-player', this.onInitIndexEditPlayer);
  };

  this.loadMain = function() {
    var viewIndexConfig, viewIndexHistory, viewIndexMatch, viewIndexPlayer;
    viewIndexMatch = this.app.addView('#view-index-match', {
      dynamicNavbar: true
    });
    viewIndexPlayer = this.app.addView('#view-index-player', {
      dynamicNavbar: true
    });
    viewIndexHistory = this.app.addView('#view-index-history', {
      dynamicNavbar: true
    });
    viewIndexConfig = this.app.addView('#view-index-control', {
      dynamicNavbar: true
    });
    viewIndexMatch.loadPage('index-match.html');
    viewIndexPlayer.loadPage('index-player.html');
    viewIndexHistory.loadPage('index-history.html');
    this.app.onPageInit('index-match', this.onInitIndexMatch);
    this.app.onPageInit('index-player', this.onInitIndexPlayer);
    this.app.onPageInit('index-history', this.onInitIndexHistory);
    this.app.onPageInit('match', this.onInitMatch);
    this.app.onPageInit('player', this.onInitPlayer);
    this.app.onPageBack('match', this.onInitIndexMatch);
    this.app.showToolbar('#toolbar');
    return this.app.showTab('#view-index-match');
  };

  this.loadLeader();

}).call(this);

//# sourceMappingURL=app.js.map
