// Generated by CoffeeScript 1.8.0
(function () {
    var $$, leftView, rightView;

    this.app = new Framework7();

    $$ = Dom7;

    leftView = this.app.addView('.view-left', {
        dynamicNavbar: true
    });

    rightView = this.app.addView('.view-main', {
        dynamicNavbar: true
    });

    this.app.onPageInit('index-match', this.onInitIndexMatch);

    this.app.onPageInit('index-player', this.onInitIndexPlayer);

    this.app.onPageInit('index-history', this.onInitIndexHistory);

    this.app.onPageInit('match', this.onInitMatch);

    this.app.onPageInit('player', this.onInitPlayer);

    this.app.onPageBack('match', this.onInitIndexMatch);

}).call(this);

//# sourceMappingURL=app.js.map
