// Generated by CoffeeScript 1.8.0
(function() {
  this.game = function() {
    return console.log("Game is a static class.");
  };

  this.game.namai = "";

  this.game.rounds = 4;

  this.game.config = function() {
    return console.log("Config is a static class.");
  };

  this.config = this.game.config;

  this.config.peace = 'no';

  this.config.score = {
    'winScore': 1,
    'peaceScore': 0,
    'byeScore': 0,
    'loseScore': 0
  };

}).call(this);

//# sourceMappingURL=config.js.map
