// Generated by CoffeeScript 1.8.0
(function () {
    this.config = function () {
    };

    this.config.peace = 'no';

    this.config.score = {
        'winScore': 1,
        'peaceScore': 0,
        'byeScore': 0,
        'loseScore': 0
    };

}).call(this);

//# sourceMappingURL=config.js.map
