// Generated by CoffeeScript 1.8.0
(function() {
  Element.prototype.smartAppend = function(str) {
    var node, parts, type, _class;
    if (typeof str !== 'string') {
      return;
    }
    type = "";
    _class = [];
    if (str.startsWith('.')) {
      type = "div";
      _class = [str.slice(1)];
    } else if (str.includes('.')) {
      parts = str.split('.');
      type = parts[0];
      _class = parts.slice(1);
    }
    if (type === "") {
      type = str;
    }
    node = this.appendChild(document.createElement(type));
    if (_class.length > 0) {
      node.classList.add(_class);
    }
    return node;
  };

  Element.prototype.smartAttribute = function(attributeName, attributeValue) {
    var attr;
    attr = document.createAttribute(attributeName);
    attr.value = attributeValue;
    this.attributes.setNamedItem(attr);
    return this;
  };

  this.createLi = function(title, after, href, data, onclick) {
    var a, inner, jq, li;
    li = $('<li></li>')[0];
    href = href || "#";
    a = li.smartAppend('a.item-link').smartAttribute("href", href);
    inner = a.smartAppend('.item-content').smartAppend('.item-inner');
    if (title) {
      $(inner.smartAppend('.item-title')).html(title);
    }
    if (after) {
      $(inner.smartAppend('.item-after')).html(after);
    }
    jq = $(li);
    if (onclick !== void 0 && onclick !== null) {
      jq.on('click', data, onclick);
    }
    return jq;
  };

}).call(this);

//# sourceMappingURL=core.js.map
