// Generated by CoffeeScript 1.8.0
(function() {
  var onEditPlayerOKPressed, onRemovePlayerOKPressed;

  this.buildEditPlayer = function() {
    var inputPlayerName;
    $('#ok-button').off('click');
    $('#ok-button').on('click', onEditPlayerOKPressed);
    if (global['index-edit-player'].player === null) {
      $('#remove-button').off('click');
      $('#remove-button').hide();
    } else {
      $('#remove-button').off('click');
      $('#remove-button').on('click', onRemovePlayerOKPressed);
      $('#remove-button').show();
    }
    inputPlayerName = $('#input-player-name')[0];
    if (global['index-edit-player'].player !== null) {
      return inputPlayerName.value = global['index-edit-player'].player.name;
    }
  };

  onEditPlayerOKPressed = function() {
    global.data.playerName = $('#input-player-name')[0].value;
    if (global.data.playername === "") {
      global.data.playername = $('#input-player-name')[0].placeholder;
    }
    if (global['index-edit-player'].player === null) {
      data.addPlayer(global.data.playerName);
    } else {
      global['index-edit-player'].player.name = global.data.playerName;
    }
    return $$('.view#view-leader')[0].f7View.router.back();
  };

  onRemovePlayerOKPressed = function() {
    data.players.splice(data.players.indexOf(global['index-edit-player'].player), 1);
    return $$('.view#view-leader')[0].f7View.router.back();
  };

}).call(this);

//# sourceMappingURL=editPlayer.js.map
