// Generated by CoffeeScript 1.8.0
(function () {
    this.global = function () {
    };

    this.global.getState = function () {
        return $('#right-pages .page.page-on-center').attr('data-page');
    };

    this.global.getLastState = function () {
    };

    this.global.getData = function () {
        return this[this.getState()];
    };

    Object.defineProperty(this.global, 'state', {
        get: this.global.getState
    });

    Object.defineProperty(this.global, 'data', {
        get: this.global.getData
    });

    this.global["index-match"] = {};

    this.global["index-history"] = {};

    this.global["index-player"] = {};

    this.global["match"] = {};

    this.global["player"] = {};

}).call(this);

//# sourceMappingURL=global.js.map
