// Generated by CoffeeScript 1.8.0
(function() {
  var createIndexHistory, createRoundHistory;

  this.buildIndexHistory = function() {
    return $('#history-list .list-group').replaceWith(createIndexHistory(round));
  };

  createIndexHistory = function() {
    var count, groupNode, round, _i, _len, _ref;
    groupNode = $('<div class="list-group"></div>');
    count = 1;
    _ref = this.data.rounds;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      round = _ref[_i];
      groupNode.append($("<div class=\"list-group-title\">第 " + count + " 轮</div>"));
      groupNode.append(createRoundHistory(round));
      count += 1;
    }
    return groupNode;
  };

  createRoundHistory = function(round) {
    var match, roundNode, _i, _len, _ref;
    roundNode = $('<ul></ul>');
    _ref = round.matches;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      match = _ref[_i];
      $(roundNode).append(createLi(match.str(), match.stateStr()));
    }
    if (round.byePlayer) {
      $(roundNode).append(createLi(round.byePlayer.name + " 轮空", "轮空"));
    }
    return roundNode;
  };

}).call(this);

//# sourceMappingURL=indexHistory.js.map
