// Generated by CoffeeScript 1.8.0
(function() {
  var createIndexPlayer;

  this.buildIndexPlayer = function(players) {
    return $('#players-list ul').replaceWith(createIndexPlayer(players));
  };

  createIndexPlayer = function(players) {
    var player, playerTitle, roundNode, _i, _len;
    roundNode = $('<ul></ul>');
    for (_i = 0, _len = players.length; _i < _len; _i++) {
      player = players[_i];
      playerTitle = ("<div class=\"badge\">" + player.score + "</div>&nbsp;") + player.name;
      $(roundNode).append(createLi(playerTitle, player.winLoseStr(), "player.html", player, function(event) {
        return global.data.player = event.data;
      }));
    }
    return roundNode;
  };

}).call(this);

//# sourceMappingURL=indexPlayer.js.map
