// Generated by CoffeeScript 1.8.0
(function() {
  this.buildIndexMatch = function(index, round) {
    global["index-match"].index = index;
    global["index-match"].round = round;
    $('#roundName').html("第 " + (index + 1) + " 轮对局");
    $('#roundMatches ul').replaceWith(createIndexMatch(round));
    return this.setIndexMatchScript();
  };

  this.createIndexMatch = function(round) {
    var match, roundNode, _i, _len, _ref;
    roundNode = $('<ul></ul>');
    _ref = round.matches;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      match = _ref[_i];
      roundNode.append(createLi(match.str(), match.stateStr(), "match.html", match, function(event) {
        return global.data.match = event.data;
      }));
    }
    return roundNode;
  };

  this.setIndexMatchScript = function() {
    $('#button-start-all-matches').off('click');
    $('#button-end-this-round').off('click');
    $('#button-start-all-matches').on('click', function() {
      data.runningRound.startAll();
      return buildIndexMatch(global.data.index, global.data.round);
    });
    return $('#button-end-this-round').on('click', function() {
      data.newRound();
      return buildIndexMatch(global.data.index + 1, data.runningRound);
    });
  };

}).call(this);

//# sourceMappingURL=indexMatch.js.map
