// Generated by CoffeeScript 1.8.0
(function() {
  var pressStart, setPlaceholder;

  this.onLeaderload = function() {
    return $('#start-button').on('click', function() {
      pressStart();
      return loadMain();
    });
  };

  pressStart = function() {
    game.namai = $('#input-game-name')[0].value;
    if (game.namai === "" || !game.namai) {
      game.namai = $('#input-game-name')[0].placeholder;
    }
    game.rounds = $('#input-game-rounds')[0].value;
    if (game.rounds === "" || !game.rounds) {
      game.rounds = $('#input-game-rounds')[0].placeholder;
    }
    return data.newRound();
  };

  setPlaceholder = function() {
    var count;
    count = Math.floor(data.players.count / 2);
    count = Math.max(count, 3);
    $('#input-game-rounds')[0].placeholder = count.toString();
    return console.log(count);
  };

}).call(this);

//# sourceMappingURL=leader.js.map
