// Generated by CoffeeScript 1.8.0
(function() {
  var pressStart, setPlaceholder;

  this.buildLeader = function() {
    setPlaceholder();
    return $('#start-button').on('click', function() {
      pressStart();
      return loadMain();
    });
  };

  pressStart = function() {
    game.namai = $('#input-game-name')[0].value;
    if (game.namai === "" || !game.namai) {
      game.namai = $('#input-game-name')[0].placeholder;
    }
    game.rounds = $('#input-game-rounds')[0].value;
    if (game.rounds === "" || !game.rounds) {
      game.rounds = $('#input-game-rounds')[0].placeholder;
    }
    game.config.peace = {
      "允许": "yes",
      "双败": "lose",
      "禁止": "no"
    }[$('#input-game-peace')[0].value];
    if (game.config.peace === 'lose') {
      game.config.score.peaceScore = 0;
    }
    return data.newRound();
  };

  setPlaceholder = function() {
    var count;
    count = Math.floor(data.players.length / 2);
    count = Math.max(count, 3);
    return $('#input-game-rounds')[0].placeholder = count.toString();
  };

}).call(this);

//# sourceMappingURL=leader.js.map
