// Generated by CoffeeScript 1.8.0
(function () {
    var buildPlayerMatches, buildPlayerText;

    this.buildPlayer = function (player) {
        $('#player-history-list ul').replaceWith(buildPlayerMatches(player));
        return $('#player-text-label').html(buildPlayerText(player));
    };

    buildPlayerText = function (player) {
        return "" + player.name + "当前 <div class=\"badge\">" + player.winCount + " - " + player.loseCount + "</div> 积 <div class=\"badge\">" + player.score + "</div> 分";
    };

    buildPlayerMatches = function (player) {
        var i, match, ul, _i, _ref, _results;
        _results = [];
        for (i = _i = 0, _ref = player.matches.length - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; i = 0 <= _ref ? ++_i : --_i) {
            ul = $("<ul></ul>");
            match = player.matches[i];
            if (match === null) {
                _results.push(ul.append(createLi("第 " + (i + 1) + " 轮 轮空", "轮空")));
            } else {
                _results.push(ul.append(createLi("第 " + (i + 1) + " 轮 对阵 " + (match.anotherPlayer(player).name), "" + (match.resultStr(player)), "match.html", match, function (event) {
                    return global.data.match = match;
                })));
            }
        }
        return _results;
    };

}).call(this);

//# sourceMappingURL=player.js.map
