// Generated by CoffeeScript 1.8.0
(function() {
  this.onInitIndexMatch = function(page) {
    return buildIndexMatch(data.rounds.length - 1, data.runningRound);
  };

  this.onInitMatch = function(page) {
    return buildMatch(global.data.match);
  };

  this.onLeaveMatch = function(page) {};

  this.onInitIndexPlayer = function(page) {
    return buildIndexPlayer(data.players);
  };

  this.onInitPlayer = function(page) {
    return buildPlayer(global.data.player);
  };

  this.onLeaveIndexPlayer = function(page) {};

  this.onInitIndexHistory = function(page) {
    return buildIndexHistory();
  };

  this.onLeaveIndexHistory = function(page) {};

}).call(this);

//# sourceMappingURL=switch.js.map
