// Generated by CoffeeScript 1.8.0
(function() {
  this.onInitIndexMatch = function(page) {
    return buildIndexMatch(data.rounds.length - 1, data.runningRound);
  };

  this.onInitMatch = function(page) {
    return buildMatch(global.data.match);
  };

  this.onInitIndexPlayer = function(page) {
    return buildIndexPlayer(data.players);
  };

  this.onInitPlayer = function(page) {
    return buildPlayer(global.data.player);
  };

  this.onInitIndexHistory = function(page) {
    return buildIndexHistory();
  };

    this.onInitLeader = function (page) {
        return buildLeader();
    };

  this.onInitIndexEditPlayer = function(page) {
    return buildIndexPlayerWithAdd(data.players);
  };

  this.onInitEditPlayer = function(page) {
    return buildEditPlayer();
  };

}).call(this);

//# sourceMappingURL=switch.js.map
