// Generated by CoffeeScript 1.8.0
(function() {
  this.data.addPlayer('熊猫');

  this.data.addPlayer('枪兵');

  this.data.addPlayer('包子');

  this.data.addPlayer('废铁');

  this.data.addPlayer('晓言');

  this.data.addPlayer('银风');

  this.data.addPlayer('败天');

  this.data.addPlayer('问号');

  this.data.addPlayer('觉皇');

}).call(this);

//# sourceMappingURL=Test.js.map
